### ISSUE TITLE
Spam drudgery

### ISSUE THREAD

**Issue by kilbith** [minetest/forum.minetest.net_template1#5]
Sorry it doesn't concerns the template but I hope the request can be better considered here.

We're currently a small bunch of caretakers reporting 5 to 15+ forum spams everyday.  This is not an efficient way for squashing them and this is tiresome (I bet for the moderators as well).

What happens if that bunch of caretakers (including moderators) will gone someday ? Or if the forum increase in popularity ? Answer : the forum will end up submerged of spams. 

We're humans and our attention is not always on the alert.
Please consider an easy captcha that could relieve us of many daily effort.

**Comment by celeron55** [comment]
I welcome any suggestions.

I personally don't have any experience on that kind of stuff related to phpBB. (Nor anything else in phpBB.)

**Comment by celeron55** [comment]
We were currently using reCaptcha, which is required when registering, and posting without registration is not allowed.

I switched it now to "GD 3D Image" for testing. It's likely that some spammers can pass it with equal efficiently because these are just the popular phpBB stock options though. We were better off with PunBB in this regard.

**Comment by ShadowNinja** [comment]
We should probably be using a plugin that checks something like [StopForumSpam](https://www.stopforumspam.com/).

**Comment by kilbith** [comment]
The standard captcha is apparently uneffective. Spammers can still pass through.
